"""Regression test: bilayer graphene density scan against saved SCF reference.

Requires contimod.  Skipped automatically when contimod is not installed.
Reference data generated by tests/generate_bilayer_reference.py.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

contimod = pytest.importorskip("contimod")
cg_symmetry = pytest.importorskip("contimod_graphene.symmetry")

import jax.numpy as jnp

import jax_hf
from jax_hf import SCFConfig, solve_scf
from jax_hf.symmetry import make_project_fn

from contimod.meanfield.init_guess import init_to_density_matrix
from contimod.utils.spectrum_fermi import FermiParams
import contimod as cm

DATA_PATH = Path(__file__).parent / "data" / "bilayer_reference.npz"
PER_CM = 0.246e-7


def _load_reference():
    """Load reference data, skip test if file missing."""
    if not DATA_PATH.exists():
        pytest.skip(f"Reference file not found: {DATA_PATH}")
    return np.load(str(DATA_PATH), allow_pickle=False)


def _build_bilayer_setup(ref):
    """Build contimod bilayer problem matching reference parameters."""
    nk = int(ref["nk"])
    kmax = float(ref["kmax"])
    U_meV = float(ref["U_meV"])
    temperature = float(ref["temperature"])
    epsilon_r = float(ref["epsilon_r"])
    d_gate = float(ref["d_gate"])
    init_scale = float(ref["init_scale"])

    model = cm.graphene.MultilayerAB(valleyful=True, spinful=True, U=U_meV)
    h_template = model.discretize(nk=nk, kmax=kmax)
    h_template.fermi = FermiParams(T=temperature, mu=0.0)

    ne_cn = float(h_template.state.compute_density_from_filling(0.5 - 1e-6))
    weights = np.asarray(h_template.kmesh.weights)

    Vq = cm.coulomb.dualgate_coulomb(
        h_template.kmesh.distance_grid, epsilon_r=epsilon_r, d_gate=d_gate,
    )
    Vq = np.asarray(Vq.magnitude)[..., None, None]

    identity_op = np.asarray(model.identity)
    s1, s2, s3 = [np.asarray(model.spin_op(i)) for i in (1, 2, 3)]
    v1, v3 = np.asarray(model.valley_op(1)), np.asarray(model.valley_op(3))
    U_tr = cg_symmetry.make_time_reversal_U(s2, v1)

    projector_sv = 0.25 * (identity_op + s3) @ (identity_op + v3)
    sv_contrast = -projector_sv + 3.0 * (identity_op - projector_sv)

    seeds = {
        "PM": h_template.get_operator("zero"),
        "SVP": -init_scale * h_template.get_operator(sv_contrast),
    }

    G_pm = cg_symmetry.make_pm_group(identity_op, s1, s2, s3, v3)
    project_fns = {
        "PM": make_project_fn(
            unitary_group=G_pm,
            time_reversal_U=jnp.asarray(U_tr),
            time_reversal_k_convention="flip",
        ),
        "SVP": cg_symmetry.make_svp_project_fn(
            s3=jnp.asarray(s3), v3=jnp.asarray(v3), n_orb=4,
            outlier_sv=(+1, +1), k_convention="flip", k_flip_axes=(0,),
        ),
    }

    return h_template, ne_cn, weights, Vq, seeds, project_fns, temperature


@pytest.fixture(scope="module")
def bilayer_setup():
    ref = _load_reference()
    setup = _build_bilayer_setup(ref)
    return ref, setup


def _run_one_point(setup, branch, n_cm12):
    """Run SCF for one branch/density combination."""
    h_template, ne_cn, weights, Vq, seeds, project_fns, temperature = setup

    dd = n_cm12 * 1e12 * (PER_CM ** 2)
    h_run = h_template.copy()
    h_run.fermi = FermiParams(T=temperature, mu=0.0)
    h_run.compute_chemicalpotential(density=float(ne_cn + dd))
    n_e = float(h_run.state.compute_density() / float(h_run.degeneracy))

    P0 = init_to_density_matrix(
        h_run, seeds[branch], density=None, T=temperature, init_kind="auto",
    )

    kernel = jax_hf.HartreeFockKernel(
        weights=weights, hamiltonian=np.asarray(h_template.hs),
        coulomb_q=Vq, T=temperature,
        include_hartree=False, include_exchange=True,
    )
    config = SCFConfig(
        max_iter=500, mixing=0.2,
        density_tol=1e-7, comm_tol=1e-6,
        project_fn=project_fns[branch],
    )
    return solve_scf(kernel, jnp.asarray(P0), n_e, config=config)


# Energy tolerance for regression: the reference was generated with the
# same solver, so results should be reproducible to float32 precision.
E_ATOL = 1e-4


@pytest.mark.parametrize("branch", ["PM", "SVP"])
@pytest.mark.parametrize("n_cm12", [-0.60, -0.42, -0.25, -0.12, -0.05, 0.05, 0.12, 0.25])
def test_scf_energy_matches_reference(bilayer_setup, branch, n_cm12):
    ref, setup = bilayer_setup
    key = f"{branch}_{n_cm12:+.2f}"

    E_ref = float(ref[f"{key}/energy"])
    converged_ref = bool(ref[f"{key}/converged"])
    if not converged_ref:
        pytest.skip(f"Reference point {key} did not converge")

    result = _run_one_point(setup, branch, n_cm12)

    assert result.converged, f"{key} did not converge: {result.message}"
    np.testing.assert_allclose(
        float(result.energy), E_ref, atol=E_ATOL,
        err_msg=f"Energy mismatch for {key}",
    )


# ---------------------------------------------------------------------------
# Direct minimization solver vs SCF reference
# ---------------------------------------------------------------------------

def _run_one_point_direct(setup, branch, n_cm12):
    """Run direct minimization solver for one branch/density combination."""
    h_template, ne_cn, weights, Vq, seeds, project_fns, temperature = setup

    dd = n_cm12 * 1e12 * (PER_CM ** 2)
    h_run = h_template.copy()
    h_run.fermi = FermiParams(T=temperature, mu=0.0)
    h_run.compute_chemicalpotential(density=float(ne_cn + dd))
    n_e = float(h_run.state.compute_density() / float(h_run.degeneracy))

    P0 = init_to_density_matrix(
        h_run, seeds[branch], density=None, T=temperature, init_kind="auto",
    )

    kernel = jax_hf.HartreeFockKernel(
        weights=weights, hamiltonian=np.asarray(h_template.hs),
        coulomb_q=Vq, T=temperature,
        include_hartree=False, include_exchange=True,
    )
    config = jax_hf.SolverConfig(
        max_iter=200, tol_E=1e-7,
        project_fn=project_fns[branch],
    )
    return jax_hf.solve(kernel, jnp.asarray(P0), n_e, config=config)


# The direct solver reaches correct energies (matching SCF to ~1e-8)
# even when the gradient hasn't formally converged to tol.
# We test energy accuracy, not gradient convergence.
DIRECT_E_ATOL = 1e-4


@pytest.mark.parametrize("branch", ["PM", "SVP"])
@pytest.mark.parametrize("n_cm12", [-0.60, -0.42, -0.25, -0.12, -0.05, 0.05, 0.12, 0.25])
def test_direct_solver_energy_matches_reference(bilayer_setup, branch, n_cm12):
    ref, setup = bilayer_setup
    key = f"{branch}_{n_cm12:+.2f}"

    E_ref = float(ref[f"{key}/energy"])
    converged_ref = bool(ref[f"{key}/converged"])
    if not converged_ref:
        pytest.skip(f"Reference point {key} did not converge")

    result = _run_one_point_direct(setup, branch, n_cm12)

    np.testing.assert_allclose(
        float(result.energy), E_ref, atol=DIRECT_E_ATOL,
        err_msg=f"Direct solver energy mismatch for {key}",
    )
