from __future__ import annotations

import numpy as np
import pytest

import jax
import jax.numpy as jnp

import jax_hf
from jax_hf.main import HartreeFockKernel
from jax_hf.symmetry import make_project_fn, make_svp_project_fn, make_svp_symmetry_group


# ---- make_project_fn unit tests (unitary_group / time_reversal) ----


def test_make_project_fn_identity_when_no_args():
    proj = make_project_fn()
    A = jnp.ones((2, 2, 3, 3), dtype=jnp.complex64)
    out = proj(A)
    np.testing.assert_array_equal(np.array(A), np.array(out))


def test_unitary_group_averaging_produces_invariant_output():
    """After projection, A should be invariant under every g in the group."""
    nb = 4
    # Z2 group generated by a diagonal sign-flip: g = diag(1,1,-1,-1)
    eye = np.eye(nb, dtype=np.complex64)
    g = np.diag(np.array([1, 1, -1, -1], dtype=np.complex64))
    G = jnp.stack([jnp.asarray(eye), jnp.asarray(g)], axis=0)

    proj = make_project_fn(unitary_group=G)

    key = jax.random.PRNGKey(42)
    a = jax.random.normal(key, (3, 3, nb, nb))
    A = (a + 1j * jax.random.normal(jax.random.PRNGKey(7), (3, 3, nb, nb))).astype(
        jnp.complex64
    )

    A_proj = proj(A)

    # Check invariance: g @ A_proj @ g† == A_proj for each g
    for i in range(G.shape[0]):
        gi = G[i]
        giH = jnp.conj(gi.T)
        rotated = (gi @ A_proj) @ giH
        np.testing.assert_allclose(
            np.array(rotated), np.array(A_proj), atol=1e-6, rtol=1e-6
        )


def test_unitary_group_averaging_is_hermitian_preserving():
    """Projecting a Hermitian matrix should produce a Hermitian result."""
    nb = 3
    eye = np.eye(nb, dtype=np.complex64)
    # Cyclic permutation matrix
    perm = np.zeros((nb, nb), dtype=np.complex64)
    perm[0, 1] = perm[1, 2] = perm[2, 0] = 1.0
    perm2 = perm @ perm
    G = jnp.stack([jnp.asarray(eye), jnp.asarray(perm), jnp.asarray(perm2)], axis=0)

    proj = make_project_fn(unitary_group=G)

    key = jax.random.PRNGKey(99)
    a = jax.random.normal(key, (2, 2, nb, nb))
    A = (a + 1j * jax.random.normal(jax.random.PRNGKey(100), (2, 2, nb, nb))).astype(
        jnp.complex64
    )
    A_herm = 0.5 * (A + jnp.conj(jnp.swapaxes(A, -1, -2)))

    result = proj(A_herm)
    np.testing.assert_allclose(
        np.array(result),
        np.array(jnp.conj(jnp.swapaxes(result, -1, -2))),
        atol=1e-6,
    )


def test_time_reversal_averaging_flip():
    """Time-reversal with 'flip' convention should produce TR-invariant output."""
    nk1, nk2, nb = 4, 4, 2
    U_tr = jnp.asarray(
        np.array([[0, -1j], [1j, 0]], dtype=np.complex64)
    )  # sigma_y * i

    proj = make_project_fn(
        time_reversal_U=U_tr, time_reversal_k_convention="flip"
    )

    key = jax.random.PRNGKey(55)
    a = jax.random.normal(key, (nk1, nk2, nb, nb))
    A = (a + 1j * jax.random.normal(jax.random.PRNGKey(56), (nk1, nk2, nb, nb))).astype(
        jnp.complex64
    )

    A_proj = proj(A)

    # Check: A_proj(k) == U conj(A_proj(-k)) U†
    UH = jnp.conj(U_tr.T)
    A_neg = jnp.flip(A_proj, axis=(0, 1))
    A_tr = U_tr @ jnp.conj(A_neg) @ UH
    np.testing.assert_allclose(
        np.array(A_proj), np.array(A_tr), atol=1e-6, rtol=1e-6
    )


def test_time_reversal_averaging_mod():
    """Time-reversal with 'mod' convention should produce TR-invariant output."""
    nk1, nk2, nb = 5, 5, 2
    U_tr = jnp.eye(nb, dtype=jnp.complex64)

    proj = make_project_fn(
        time_reversal_U=U_tr, time_reversal_k_convention="mod"
    )

    key = jax.random.PRNGKey(77)
    a = jax.random.normal(key, (nk1, nk2, nb, nb))
    A = (a + 1j * jax.random.normal(jax.random.PRNGKey(78), (nk1, nk2, nb, nb))).astype(
        jnp.complex64
    )

    A_proj = proj(A)

    # Check mod-convention TR invariance
    UH = jnp.conj(U_tr.T)
    i_idx = (-jnp.arange(nk1, dtype=jnp.int32)) % nk1
    j_idx = (-jnp.arange(nk2, dtype=jnp.int32)) % nk2
    A_neg = A_proj[i_idx[:, None], j_idx[None, :], ...]
    A_tr = U_tr @ jnp.conj(A_neg) @ UH
    np.testing.assert_allclose(
        np.array(A_proj), np.array(A_tr), atol=1e-6, rtol=1e-6
    )


def test_combined_unitary_and_time_reversal():
    """Combined group + TR projection should be invariant under both."""
    nk1, nk2, nb = 4, 4, 2
    eye = np.eye(nb, dtype=np.complex64)
    sigma_z = np.diag(np.array([1, -1], dtype=np.complex64))
    G = jnp.stack([jnp.asarray(eye), jnp.asarray(sigma_z)], axis=0)
    U_tr = jnp.eye(nb, dtype=jnp.complex64)

    proj = make_project_fn(
        unitary_group=G,
        time_reversal_U=U_tr,
        time_reversal_k_convention="flip",
    )

    key = jax.random.PRNGKey(11)
    a = jax.random.normal(key, (nk1, nk2, nb, nb))
    A = (a + 1j * jax.random.normal(jax.random.PRNGKey(12), (nk1, nk2, nb, nb))).astype(
        jnp.complex64
    )

    A_proj = proj(A)

    # Check group invariance
    for i in range(G.shape[0]):
        gi = G[i]
        giH = jnp.conj(gi.T)
        rotated = (gi @ A_proj) @ giH
        np.testing.assert_allclose(
            np.array(rotated), np.array(A_proj), atol=1e-5, rtol=1e-5
        )

    # Check TR invariance
    UH = jnp.conj(U_tr.T)
    A_neg = jnp.flip(A_proj, axis=(0, 1))
    A_tr = U_tr @ jnp.conj(A_neg) @ UH
    np.testing.assert_allclose(
        np.array(A_proj), np.array(A_tr), atol=1e-5, rtol=1e-5
    )


def test_projection_is_idempotent():
    """Applying projection twice should give the same result as once."""
    nb = 3
    eye = np.eye(nb, dtype=np.complex64)
    perm = np.zeros((nb, nb), dtype=np.complex64)
    perm[0, 1] = perm[1, 2] = perm[2, 0] = 1.0
    perm2 = perm @ perm
    G = jnp.stack([jnp.asarray(eye), jnp.asarray(perm), jnp.asarray(perm2)], axis=0)

    proj = make_project_fn(unitary_group=G)

    key = jax.random.PRNGKey(0)
    A = jax.random.normal(key, (2, 2, nb, nb), dtype=jnp.float32).astype(
        jnp.complex64
    )

    once = proj(A)
    twice = proj(once)
    np.testing.assert_allclose(np.array(once), np.array(twice), atol=1e-6)


# ---- spatial_group (combined same-k + flip-k) tests ----


def test_spatial_group_produces_k_flip_invariant_output():
    """Projection with spatial_group should be invariant under g·A(-k)·g†."""
    nk1, nk2, nb = 4, 4, 2
    # A single spatial element: sigma_x acts at -k
    sigma_x = np.array([[0, 1], [1, 0]], dtype=np.complex64)
    S = jnp.asarray(sigma_x)[None]  # (1, 2, 2)

    proj = make_project_fn(spatial_group=S, spatial_k_convention="flip")

    key = jax.random.PRNGKey(33)
    A = jax.random.normal(key, (nk1, nk2, nb, nb)).astype(jnp.complex64)

    A_proj = proj(A)

    # Check: A_proj(k) == sigma_x @ A_proj(-k) @ sigma_x†
    sxH = jnp.conj(sigma_x.T)
    A_neg = jnp.flip(A_proj, axis=(0, 1))
    A_rotated = jnp.asarray(sigma_x) @ A_neg @ jnp.asarray(sxH)
    np.testing.assert_allclose(
        np.array(A_proj), np.array(A_rotated), atol=1e-6, rtol=1e-6
    )


def test_combined_same_k_and_flip_k_group():
    """Test combined group averaging with explicit same-k and flip-k elements."""
    nk1, nk2, nb = 4, 4, 2
    eye = np.eye(nb, dtype=np.complex64)
    sigma_z = np.diag(np.array([1, -1], dtype=np.complex64))
    sigma_x = np.array([[0, 1], [1, 0]], dtype=np.complex64)

    # Group: {I at same-k, sigma_z at same-k, sigma_x at flip-k}
    G_same = jnp.stack([jnp.asarray(eye), jnp.asarray(sigma_z)], axis=0)
    G_flip = jnp.asarray(sigma_x)[None]

    proj = make_project_fn(
        unitary_group=G_same,
        spatial_group=G_flip,
        spatial_k_convention="flip",
    )

    key = jax.random.PRNGKey(44)
    A = jax.random.normal(key, (nk1, nk2, nb, nb)).astype(jnp.complex64)

    A_proj = proj(A)

    # Verify: the projection is (1/3)[I·A·I† + σz·A·σz† + σx·A(-k)·σx†]
    A_neg = jnp.flip(A, axis=(0, 1))
    expected = (
        A
        + jnp.asarray(sigma_z) @ A @ jnp.conj(jnp.asarray(sigma_z).T)
        + jnp.asarray(sigma_x) @ A_neg @ jnp.conj(jnp.asarray(sigma_x).T)
    ) / 3.0
    np.testing.assert_allclose(
        np.array(A_proj), np.array(expected), atol=1e-6, rtol=1e-6
    )


def test_combined_group_is_idempotent():
    """Combined same-k + flip-k projection should be idempotent."""
    nk1, nk2, nb = 4, 4, 2
    eye = np.eye(nb, dtype=np.complex64)
    sigma_z = np.diag(np.array([1, -1], dtype=np.complex64))
    sigma_x = np.array([[0, 1], [1, 0]], dtype=np.complex64)

    # {I, sigma_z} at same-k, {sigma_x} at flip-k
    # NOTE: this is NOT a group (not closed under composition).
    # So idempotency is not guaranteed in general.
    # Use a proper group instead: Z2 = {I at same-k, sigma_x at flip-k}
    G_same = jnp.asarray(eye)[None]
    G_flip = jnp.asarray(sigma_x)[None]

    proj = make_project_fn(
        unitary_group=G_same,
        spatial_group=G_flip,
        spatial_k_convention="flip",
    )

    key = jax.random.PRNGKey(55)
    A = jax.random.normal(key, (nk1, nk2, nb, nb)).astype(jnp.complex64)

    once = proj(A)
    twice = proj(once)
    np.testing.assert_allclose(np.array(once), np.array(twice), atol=1e-5)


# ---- kx-only flip (spatial_k_flip_axes) tests ----


def test_spatial_group_kx_only_flip():
    """spatial_k_flip_axes=(0,) should flip only the kx axis."""
    nk1, nk2, nb = 5, 4, 2
    sigma_x = np.array([[0, 1], [1, 0]], dtype=np.complex64)
    S = jnp.asarray(sigma_x)[None]

    proj = make_project_fn(
        spatial_group=S,
        spatial_k_convention="flip",
        spatial_k_flip_axes=(0,),
    )

    key = jax.random.PRNGKey(88)
    A = jax.random.normal(key, (nk1, nk2, nb, nb)).astype(jnp.complex64)

    A_proj = proj(A)

    # Check: A_proj(kx, ky) == sigma_x @ A_proj(-kx, ky) @ sigma_x†
    sxH = jnp.conj(sigma_x.T)
    A_kx_flip = jnp.flip(A_proj, axis=(0,))  # flip only kx
    A_rotated = jnp.asarray(sigma_x) @ A_kx_flip @ jnp.asarray(sxH)
    np.testing.assert_allclose(
        np.array(A_proj), np.array(A_rotated), atol=1e-6, rtol=1e-6
    )


def test_kx_only_flip_is_idempotent():
    """kx-only flip projection should be idempotent for a proper Z2 group."""
    nk1, nk2, nb = 6, 4, 2
    eye = np.eye(nb, dtype=np.complex64)
    sigma_x = np.array([[0, 1], [1, 0]], dtype=np.complex64)
    G_same = jnp.asarray(eye)[None]
    G_flip = jnp.asarray(sigma_x)[None]

    proj = make_project_fn(
        unitary_group=G_same,
        spatial_group=G_flip,
        spatial_k_convention="flip",
        spatial_k_flip_axes=(0,),
    )

    key = jax.random.PRNGKey(66)
    A = jax.random.normal(key, (nk1, nk2, nb, nb)).astype(jnp.complex64)

    once = proj(A)
    twice = proj(once)
    np.testing.assert_allclose(np.array(once), np.array(twice), atol=1e-5)


def test_kx_only_flip_differs_from_full_flip():
    """kx-only and full k-flip should give different results on asymmetric input."""
    nk1, nk2, nb = 5, 5, 2
    sigma_x = np.array([[0, 1], [1, 0]], dtype=np.complex64)
    S = jnp.asarray(sigma_x)[None]

    proj_full = make_project_fn(
        spatial_group=S, spatial_k_convention="flip", spatial_k_flip_axes=(0, 1),
    )
    proj_kx = make_project_fn(
        spatial_group=S, spatial_k_convention="flip", spatial_k_flip_axes=(0,),
    )

    # Build an input that is NOT ky-symmetric, so the two projections differ.
    key = jax.random.PRNGKey(77)
    A = jax.random.normal(key, (nk1, nk2, nb, nb)).astype(jnp.complex64)

    A_full = proj_full(A)
    A_kx = proj_kx(A)

    # They should generally differ (extremely unlikely to match by chance).
    assert not np.allclose(np.array(A_full), np.array(A_kx), atol=1e-4)


def test_svp_group_kx_only_flip_permutes_sectors():
    """SVP group with kx-only flip should still equalize 3 inactive sectors."""
    ops = _make_spin_valley_ops(nb_per_sector=1)
    same_k, flip_k = make_svp_symmetry_group(
        **{k: jnp.asarray(v) for k, v in ops.items()},
        outlier_sv=(+1, +1),
    )
    proj = make_project_fn(
        unitary_group=same_k,
        spatial_group=flip_k,
        spatial_k_convention="flip",
        spatial_k_flip_axes=(0,),
    )

    # Single k-point: kx-flip = identity since grid is 1×1
    A = jnp.diag(jnp.array([1.0, 2.0, 3.0, 4.0], dtype=jnp.complex64))
    A = A[None, None, ...]

    A_proj = proj(A)
    d = jnp.real(jnp.diag(A_proj[0, 0]))

    assert float(d[0]) == pytest.approx(1.0, abs=1e-5)
    assert float(d[1]) == pytest.approx(3.0, abs=1e-5)
    assert float(d[2]) == pytest.approx(3.0, abs=1e-5)
    assert float(d[3]) == pytest.approx(3.0, abs=1e-5)


def test_svp_group_kx_only_flip_multi_k_idempotent():
    """SVP group with kx-only flip and multiple k-points should be idempotent."""
    ops = _make_spin_valley_ops(nb_per_sector=1)
    same_k, flip_k = make_svp_symmetry_group(
        **{k: jnp.asarray(v) for k, v in ops.items()},
        outlier_sv=(+1, +1),
    )
    proj = make_project_fn(
        unitary_group=same_k,
        spatial_group=flip_k,
        spatial_k_convention="flip",
        spatial_k_flip_axes=(0,),
    )

    key = jax.random.PRNGKey(101)
    A = jax.random.normal(key, (5, 4, 4, 4)).astype(jnp.complex64)
    A = 0.5 * (A + jnp.conj(jnp.swapaxes(A, -1, -2)))

    once = proj(A)
    twice = proj(once)
    np.testing.assert_allclose(np.array(once), np.array(twice), atol=1e-5)


# ---- make_svp_symmetry_group tests ----


def _make_spin_valley_ops(nb_per_sector: int = 1):
    """Build toy spin/valley operators for nb = 4 * nb_per_sector.

    Returns a dict with keys: identity, s1, s3, v_rotation, v3.
    In this toy model (no orbital structure), v_rotation is just
    Pauli-X in valley space (equivalent to the simple valley flip).
    """
    nb = 4 * nb_per_sector
    # Sector ordering: K↑, K↓, K'↑, K'↓
    # s3: +1 for ↑, -1 for ↓;  v3: +1 for K, -1 for K'
    s3_diag = np.array([+1, -1, +1, -1] * nb_per_sector, dtype=np.float32)
    v3_diag = np.array([+1, +1, -1, -1] * nb_per_sector, dtype=np.float32)

    identity = np.eye(nb, dtype=np.complex64)
    s3 = np.diag(s3_diag.astype(np.complex64))
    v3 = np.diag(v3_diag.astype(np.complex64))

    # s1 flips spin (swaps ↑↔↓ within each valley)
    s1 = np.zeros((nb, nb), dtype=np.complex64)
    for base in range(0, nb, 2 * nb_per_sector):
        for i in range(nb_per_sector):
            s1[base + i, base + nb_per_sector + i] = 1.0
            s1[base + nb_per_sector + i, base + i] = 1.0

    # v_rotation flips valley (swaps K↔K' within each spin).
    # In this toy model there are no orbitals to rotate, so it's
    # just Pauli-X in valley space.
    v_rotation = np.zeros((nb, nb), dtype=np.complex64)
    half = 2 * nb_per_sector
    for i in range(half):
        v_rotation[i, i + half] = 1.0
        v_rotation[i + half, i] = 1.0

    return dict(identity=identity, s1=s1, s3=s3, v_rotation=v_rotation, v3=v3)


def test_svp_group_has_correct_shape():
    ops = _make_spin_valley_ops(nb_per_sector=1)
    same_k, flip_k = make_svp_symmetry_group(
        **{k: jnp.asarray(v) for k, v in ops.items()}
    )
    # 3 same-k elements (even permutations): {I, C1, C2}
    assert same_k.shape == (3, 4, 4)
    # 3 flip-k elements (odd permutations / transpositions): {T_AB, T_AC, T_BC}
    assert flip_k.shape == (3, 4, 4)

    # Each element should be unitary
    for label, arr in [("same_k", same_k), ("flip_k", flip_k)]:
        for i in range(arr.shape[0]):
            g = np.array(arr[i])
            np.testing.assert_allclose(
                g @ g.conj().T, np.eye(4), atol=1e-5,
                err_msg=f"{label}[{i}] not unitary",
            )


def test_svp_group_permutes_three_sectors_fixes_outlier():
    """S₃ averaging should equalize 3 non-outlier diagonal blocks, leave outlier free.

    With a single k-point, k=-k=0, so same-k and flip-k elements are
    equivalent.  This validates the group structure on diagonal matrices.
    """
    ops = _make_spin_valley_ops(nb_per_sector=1)
    same_k, flip_k = make_svp_symmetry_group(
        **{k: jnp.asarray(v) for k, v in ops.items()},
        outlier_sv=(+1, +1),  # K↑ is the outlier
    )
    proj = make_project_fn(
        unitary_group=same_k,
        spatial_group=flip_k,
        spatial_k_convention="flip",
    )

    # Build a diagonal matrix with 4 different sector values
    # Sectors: K↑=0, K↓=1, K'↑=2, K'↓=3
    A = jnp.diag(jnp.array([1.0, 2.0, 3.0, 4.0], dtype=jnp.complex64))
    A = A[None, None, ...]  # (1,1,4,4) — single k-point

    A_proj = proj(A)
    d = jnp.real(jnp.diag(A_proj[0, 0]))

    # K↑ (index 0) should be unchanged: 1.0
    assert float(d[0]) == pytest.approx(1.0, abs=1e-5)
    # K↓, K'↑, K'↓ (indices 1,2,3) should all be averaged: (2+3+4)/3 = 3.0
    assert float(d[1]) == pytest.approx(3.0, abs=1e-5)
    assert float(d[2]) == pytest.approx(3.0, abs=1e-5)
    assert float(d[3]) == pytest.approx(3.0, abs=1e-5)


def test_svp_group_different_outlier():
    """Changing outlier_sv should change which sector is left free."""
    ops = _make_spin_valley_ops(nb_per_sector=1)

    # outlier = K'↓ = (-1, -1)
    same_k, flip_k = make_svp_symmetry_group(
        **{k: jnp.asarray(v) for k, v in ops.items()},
        outlier_sv=(-1, -1),
    )
    proj = make_project_fn(
        unitary_group=same_k,
        spatial_group=flip_k,
        spatial_k_convention="flip",
    )

    A = jnp.diag(jnp.array([1.0, 2.0, 3.0, 4.0], dtype=jnp.complex64))
    A = A[None, None, ...]

    A_proj = proj(A)
    d = jnp.real(jnp.diag(A_proj[0, 0]))

    # K'↓ (index 3) should be unchanged: 4.0
    assert float(d[3]) == pytest.approx(4.0, abs=1e-5)
    # K↑, K↓, K'↑ (indices 0,1,2) should all be averaged: (1+2+3)/3 = 2.0
    assert float(d[0]) == pytest.approx(2.0, abs=1e-5)
    assert float(d[1]) == pytest.approx(2.0, abs=1e-5)
    assert float(d[2]) == pytest.approx(2.0, abs=1e-5)


def test_svp_group_idempotent():
    """Applying SVP projection twice should give the same result as once."""
    ops = _make_spin_valley_ops(nb_per_sector=1)
    same_k, flip_k = make_svp_symmetry_group(
        **{k: jnp.asarray(v) for k, v in ops.items()}
    )
    proj = make_project_fn(
        unitary_group=same_k,
        spatial_group=flip_k,
        spatial_k_convention="flip",
    )

    key = jax.random.PRNGKey(42)
    A = jax.random.normal(key, (2, 2, 4, 4)).astype(jnp.complex64)

    once = proj(A)
    twice = proj(once)
    np.testing.assert_allclose(np.array(once), np.array(twice), atol=1e-5)


def test_svp_group_multi_k_respects_k_flip():
    """With multiple k-points, SVP flip-k elements should map A(k)↔A(-k)."""
    ops = _make_spin_valley_ops(nb_per_sector=1)
    same_k, flip_k = make_svp_symmetry_group(
        **{k: jnp.asarray(v) for k, v in ops.items()},
        outlier_sv=(+1, +1),
    )
    proj = make_project_fn(
        unitary_group=same_k,
        spatial_group=flip_k,
        spatial_k_convention="flip",
    )

    nk1, nk2 = 4, 4
    key = jax.random.PRNGKey(99)
    A = jax.random.normal(key, (nk1, nk2, 4, 4)).astype(jnp.complex64)
    # Make Hermitian
    A = 0.5 * (A + jnp.conj(jnp.swapaxes(A, -1, -2)))

    A_proj = proj(A)

    # Verify idempotency with the multi-k grid
    twice = proj(A_proj)
    np.testing.assert_allclose(np.array(A_proj), np.array(twice), atol=1e-5)

    # Verify the result is Hermitian
    np.testing.assert_allclose(
        np.array(A_proj),
        np.array(jnp.conj(jnp.swapaxes(A_proj, -1, -2))),
        atol=1e-6,
    )


# ---- Integration: variational solver with project_fn ----


def test_variational_solver_with_project_fn_converges():
    """Variational solver with a Z2 symmetry projection should converge."""
    nk1, nk2, nb = 1, 1, 4
    # Block-diagonal Hamiltonian respecting the Z2 symmetry
    h_arr = np.zeros((nk1, nk2, nb, nb), dtype=np.complex64)
    h_arr[0, 0] = np.diag([-1.0, -0.5, 0.5, 1.0])
    h_arr[0, 0, 0, 1] = h_arr[0, 0, 1, 0] = 0.2
    h_arr[0, 0, 2, 3] = h_arr[0, 0, 3, 2] = 0.2
    hamiltonian = jnp.asarray(h_arr)

    weights = jnp.ones((nk1, nk2), dtype=jnp.float32)
    coulomb_q = (0.05 * jnp.ones((nk1, nk2, 1, 1), dtype=jnp.float32)).astype(
        jnp.complex64
    )

    kernel = HartreeFockKernel(
        weights=weights,
        hamiltonian=hamiltonian,
        coulomb_q=coulomb_q,
        T=0.1,
        include_hartree=False,
        include_exchange=True,
    )

    # Z2 group: g = diag(1,1,-1,-1)
    eye = np.eye(nb, dtype=np.complex64)
    g = np.diag(np.array([1, 1, -1, -1], dtype=np.complex64))
    G = jnp.stack([jnp.asarray(eye), jnp.asarray(g)], axis=0)
    proj = make_project_fn(unitary_group=G)

    runner = jax_hf.jit_variational_hartreefock_iteration(kernel)

    P0 = 0.5 * jnp.eye(nb, dtype=jnp.complex64)[None, None, ...]

    P_fin, F_fin, E_fin, mu_fin, k_fin, history = runner(
        P0,
        electrondensity0=2.0,
        max_iter=80,
        comm_tol=1e-5,
        p_tol=1e-5,
        project_fn=proj,
    )

    assert np.isfinite(np.array(E_fin)).all()
    assert int(k_fin) < 80

    # P_fin should be invariant under the Z2 symmetry
    g_j = jnp.asarray(g)
    gH = jnp.conj(g_j.T)
    P_rotated = (g_j @ P_fin) @ gH
    np.testing.assert_allclose(
        np.array(P_fin), np.array(P_rotated), atol=1e-5, rtol=1e-5
    )

    # F_fin should also be invariant
    F_rotated = (g_j @ F_fin) @ gH
    np.testing.assert_allclose(
        np.array(F_fin), np.array(F_rotated), atol=1e-5, rtol=1e-5
    )


def test_variational_solver_without_project_fn_unchanged():
    """project_fn=None should produce identical results to no project_fn."""
    weights = jnp.ones((1, 1), dtype=jnp.float32)
    hamiltonian = jnp.array([[[[-0.5, 0.0], [0.0, 0.5]]]], dtype=jnp.complex64)
    coulomb_q = jnp.array([[[[0.25]]]], dtype=jnp.complex64)

    kernel = HartreeFockKernel(
        weights=weights,
        hamiltonian=hamiltonian,
        coulomb_q=coulomb_q,
        T=0.2,
        include_hartree=False,
        include_exchange=True,
    )
    runner = jax_hf.jit_variational_hartreefock_iteration(kernel)

    P0 = jnp.array([[[[0.6, 0.0], [0.0, 0.4]]]], dtype=jnp.complex64)
    kwargs = dict(
        electrondensity0=1.0,
        max_iter=40,
        comm_tol=1e-6,
        p_tol=1e-6,
    )

    P_none, _F_none, E_none, mu_none, k_none, hist_none = runner(P0, **kwargs)
    P_expl, _F_expl, E_expl, mu_expl, k_expl, hist_expl = runner(
        P0, project_fn=None, **kwargs
    )

    np.testing.assert_allclose(np.array(P_none), np.array(P_expl), atol=1e-7)
    assert float(E_none) == pytest.approx(float(E_expl), abs=1e-7)
    assert int(k_none) == int(k_expl)


# ---- make_svp_project_fn tests ----


def _make_svp_project_ops(nb_per_sector: int = 1):
    """Build s3, v3 for 4-sector SVP projection tests."""
    nb = 4 * nb_per_sector
    s3 = np.diag(np.tile([+1, +1, -1, -1], nb_per_sector).astype(np.complex64))
    v3 = np.diag(np.tile([+1, -1, +1, -1], nb_per_sector).astype(np.complex64))
    return s3, v3


def test_svp_project_fn_equalises_inactive_blocks():
    """SVP project should equalize 3 inactive blocks and leave outlier free."""
    s3, v3 = _make_svp_project_ops(nb_per_sector=1)
    proj = make_svp_project_fn(
        s3=jnp.asarray(s3),
        v3=jnp.asarray(v3),
        n_orb=1,
        outlier_sv=(+1, +1),
        k_convention="flip",
        k_flip_axes=(0,),
    )

    # Single k-point: kx-flip = identity on 1x1 grid
    A = jnp.diag(jnp.array([1.0, 2.0, 3.0, 4.0], dtype=jnp.complex64))
    A = A[None, None, ...]

    A_proj = proj(A)
    d = jnp.real(jnp.diag(A_proj[0, 0]))

    # Outlier K↑ (index 0) should be unchanged
    assert float(d[0]) == pytest.approx(1.0, abs=1e-5)
    # Inactive blocks (indices 1, 2, 3) should all be averaged: (2+3+4)/3 = 3.0
    assert float(d[1]) == pytest.approx(3.0, abs=1e-5)
    assert float(d[2]) == pytest.approx(3.0, abs=1e-5)
    assert float(d[3]) == pytest.approx(3.0, abs=1e-5)


def test_svp_project_fn_zeros_off_diagonal_blocks():
    """SVP project should zero all inter-flavour coherences."""
    s3, v3 = _make_svp_project_ops(nb_per_sector=1)
    proj = make_svp_project_fn(
        s3=jnp.asarray(s3), v3=jnp.asarray(v3), n_orb=1,
        outlier_sv=(+1, +1), k_convention="flip", k_flip_axes=(0,),
    )

    A = jnp.ones((1, 1, 4, 4), dtype=jnp.complex64)
    A_proj = proj(A)

    # Off-diagonal blocks should be zero
    for i in range(4):
        for j in range(4):
            if i != j:
                assert float(jnp.abs(A_proj[0, 0, i, j])) == pytest.approx(
                    0.0, abs=1e-6
                )


def test_svp_project_fn_does_not_force_k_symmetry_on_outlier():
    """The outlier block should NOT be averaged with its kx-flipped version."""
    s3, v3 = _make_svp_project_ops(nb_per_sector=1)
    proj = make_svp_project_fn(
        s3=jnp.asarray(s3), v3=jnp.asarray(v3), n_orb=1,
        outlier_sv=(+1, +1), k_convention="flip", k_flip_axes=(0,),
    )

    nk1, nk2 = 5, 3
    # Build input where the outlier block varies with kx (NOT kx-symmetric)
    key = jax.random.PRNGKey(42)
    A = jax.random.normal(key, (nk1, nk2, 4, 4)).astype(jnp.complex64)
    # Make Hermitian
    A = 0.5 * (A + jnp.conj(jnp.swapaxes(A, -1, -2)))

    A_proj = proj(A)

    # Outlier block (0, 0) should be EXACTLY the original (not averaged)
    np.testing.assert_allclose(
        np.array(A_proj[..., 0:1, 0:1]),
        np.array(A[..., 0:1, 0:1]),
        atol=1e-7,
    )

    # But the outlier block should NOT have kx-symmetry in general
    outlier_orig = np.array(A[..., 0, 0])  # (nk1, nk2)
    outlier_kx_flip = np.flip(outlier_orig, axis=0)
    assert not np.allclose(outlier_orig, outlier_kx_flip, atol=1e-3)


def test_svp_project_fn_is_idempotent():
    """Applying SVP projection twice should give the same result as once."""
    s3, v3 = _make_svp_project_ops(nb_per_sector=1)
    proj = make_svp_project_fn(
        s3=jnp.asarray(s3), v3=jnp.asarray(v3), n_orb=1,
        outlier_sv=(+1, +1), k_convention="flip", k_flip_axes=(0,),
    )

    nk1, nk2 = 6, 4
    key = jax.random.PRNGKey(99)
    A = jax.random.normal(key, (nk1, nk2, 4, 4)).astype(jnp.complex64)
    A = 0.5 * (A + jnp.conj(jnp.swapaxes(A, -1, -2)))

    once = proj(A)
    twice = proj(once)
    np.testing.assert_allclose(np.array(once), np.array(twice), atol=1e-6)


def test_svp_project_fn_different_outlier():
    """Changing outlier should change which block is left free."""
    s3, v3 = _make_svp_project_ops(nb_per_sector=1)

    # outlier = K'↓ = (-1, -1) = block index 3
    proj = make_svp_project_fn(
        s3=jnp.asarray(s3), v3=jnp.asarray(v3), n_orb=1,
        outlier_sv=(-1, -1), k_convention="flip", k_flip_axes=(0,),
    )

    A = jnp.diag(jnp.array([1.0, 2.0, 3.0, 4.0], dtype=jnp.complex64))
    A = A[None, None, ...]

    A_proj = proj(A)
    d = jnp.real(jnp.diag(A_proj[0, 0]))

    # K'↓ (index 3) should be unchanged: 4.0
    assert float(d[3]) == pytest.approx(4.0, abs=1e-5)
    # K↑, K'↑, K↓ (indices 0, 1, 2) should all be averaged: (1+2+3)/3 = 2.0
    assert float(d[0]) == pytest.approx(2.0, abs=1e-5)
    assert float(d[1]) == pytest.approx(2.0, abs=1e-5)
    assert float(d[2]) == pytest.approx(2.0, abs=1e-5)


def test_svp_project_fn_multi_orb_idempotent():
    """SVP projection with n_orb > 1 should be idempotent."""
    n_orb = 2
    nb = 4 * n_orb
    s3 = np.diag(np.array([+1]*n_orb + [+1]*n_orb + [-1]*n_orb + [-1]*n_orb,
                           dtype=np.complex64))
    v3 = np.diag(np.array([+1]*n_orb + [-1]*n_orb + [+1]*n_orb + [-1]*n_orb,
                           dtype=np.complex64))
    proj = make_svp_project_fn(
        s3=jnp.asarray(s3), v3=jnp.asarray(v3), n_orb=n_orb,
        outlier_sv=(+1, +1), k_convention="flip", k_flip_axes=(0,),
    )

    nk1, nk2 = 5, 5
    key = jax.random.PRNGKey(77)
    A = jax.random.normal(key, (nk1, nk2, nb, nb)).astype(jnp.complex64)
    A = 0.5 * (A + jnp.conj(jnp.swapaxes(A, -1, -2)))

    once = proj(A)
    twice = proj(once)
    np.testing.assert_allclose(np.array(once), np.array(twice), atol=1e-5)
