name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist and wheel
        run: |
          python -m pip install -U pip build
          python -m build -s -w

      - name: Install wheel and smoke-check metadata
        run: |
          python -m pip install dist/*.whl
          python - << 'PY'
          import importlib.metadata as md
          print("jax_hf version:", md.version("jax_hf"))
          PY

