name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # 👇 This must match exactly the environment you configure on PyPI
    environment: jax_hf_env
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist and wheel
        run: |
          python -m pip install -U pip build
          python -m build -s -w

      - name: Smoke-check package metadata
        run: |
          python -m pip install dist/*.whl
          python - << 'PY'
          import importlib.metadata as md
          print("jax_hf version:", md.version("jax_hf"))
          PY

      # Only publish on tag refs like v0.1.0
      - name: Publish to PyPI via OIDC (Trusted Publisher)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
